apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    spec:
      containers:
        - name: argocd-server
          resources:
            requests:
              cpu: 150m
              memory: 76Mi
            limits:
              memory: 256Mi