---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
  template:
    spec:
      containers:
        - name: dex
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              memory: 64Mi
          env:
            - name: ARGO_WORKFLOWS_KUBE_0002_SSO
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: argo-workflows-kube0002-sso
      initContainers:
        - name: copyutil

