---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-redis-ha-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis-ha
  serviceName: argocd-redis-ha
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              cpu: 15m
              memory: 76Mi
            limits:
              memory: 256Mi

