apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - target:
      kind: Ingress
      name: argocd
      namespace: argocd
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: argocd.menno.test
  - target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    patch: |-
      - op: replace
        path: /data/url
        value: https://argocd.menno.test