---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://github.com/Men-io/cd-five-mins-local-test.git
    targetRevision: main
    path: argocd-definitions/dev
    helm:
      parameters:
        - name: cluster
          value: https://kubernetes.default.svc
        - name: clusterName
          value: test
        - name: clusterType
          value: test
        - name: environment
          value: dev
      valueFiles:
        - 'values.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

