# kustomize edit set image quay.io/codefresh_sa/express-microservice:test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: codefresh

images:
  - name: quay.io/codefresh_sa/express
    newTag: "5416e81"
