---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Release.Name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Admin project for {{ .Release.Name }}
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: {{ .Values.cluster }}
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
