---
{{ if .Values.apps.metricsServerVersion }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: metrics
    server: {{ .Values.cluster | quote }}
  source:
    path: ./k8s-resources/kube-state-metrics/dev
    repoURL: https://github.com/Men-io/cd-five-mins-local-test.git
    targetRevision: {{ .Values.apps.metricsServerVersion | quote }}
    helm:
      releaseName: metrics-server #this prevents using the argocd app name as release name.
      valueFiles:
        - values.yaml
  project: {{ .Release.Name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}